config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get 'up' => 'rails/health#show', as: :rails_health_check

  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy

  # Defines the root path route ("/")
  root to: "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, presence: true
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    # @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = @list
    # @bookmarks.list_id = @list.id
    if @bookmark.save
      redirect_to list_path(@list), notice: "Bookmark was successfully created."
    else
      # @review = Review.new
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
    set_list
  end

   # GET /lists/new
   def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    set_list
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

   # PATCH/PUT /restaurants/1
   def update
    if @list.update(list_params)
      redirect_to @list, notice: "List was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  #DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :photo)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
          <%= f.association :movie, prompt: "Select a movie", input_html: {data: {controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div>
  <%= link_to "Back to lists", lists_path, class: "btn btn-primary"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <%= f.input :photo, as: :file %>

  <div class="form-actions">
    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
  <h1>Lists</h1>
    <% @lists.each do |list| %>
      <%= list.name %>
      <p>
        <%= link_to "Show this list", list, class: "btn btn-secondary" %>
      </p>
    <% end %>

    <p>
      <%= link_to "Crate a new list", new_list_path, class: "btn btn-primary" %>
    </p>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div>
  <h2>
    <strong>Name:</strong>
    <%= @list.name %>
  </h2>
  <h3>Bookmarks:</h3>
<% @list.bookmarks.each do |bookmark| %>
  <p><%= bookmark.comment %></p>
  <%= link_to "Delete this bookmark", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
<% end %>
</div>
<% if @list.photo.attached?  %>
 <%= cl_image_tag @list.photo.key, height: 300, width: 300, crop: :fill %>
 <% else %>
 <%#= image_tag "logo.png" %>
  <h1>No picture!</h1>
 <% end %>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %> |
  <%= link_to "Create a new bookmark",  new_list_bookmark_path(@list) %>
  <%= button_to "Destroy this list", @list, method: :delete %>
</div>